// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.EntityFramework;

namespace SB.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SB.Core.Entities.Entity_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 276, DateTimeKind.Local).AddTicks(1149),
                            IsDeleted = false,
                            Name = "Tables",
                            UpdatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 278, DateTimeKind.Local).AddTicks(1881)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 278, DateTimeKind.Local).AddTicks(4116),
                            IsDeleted = false,
                            Name = "Chairs",
                            UpdatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 278, DateTimeKind.Local).AddTicks(4137)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 278, DateTimeKind.Local).AddTicks(4142),
                            IsDeleted = false,
                            Name = "Wardroabs",
                            UpdatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 278, DateTimeKind.Local).AddTicks(4144)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 278, DateTimeKind.Local).AddTicks(4147),
                            IsDeleted = false,
                            Name = "Beds",
                            UpdatedOn = new DateTime(2022, 6, 13, 18, 47, 33, 278, DateTimeKind.Local).AddTicks(4149)
                        });
                });

            modelBuilder.Entity("SB.Core.Entities.Entity_Item", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Category_ID_FK")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Category_ID_FK");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SB.Core.Entities.Entity_Item", b =>
                {
                    b.HasOne("SB.Core.Entities.Entity_Category", "Entity_Category")
                        .WithMany()
                        .HasForeignKey("Category_ID_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity_Category");
                });
#pragma warning restore 612, 618
        }
    }
}
